---
- name: Ensure output directory exists
  ansible.builtin.file:
    path: "{{ output_dir }}"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Set golden config path (static folder)
  ansible.builtin.set_fact:
    golden_config_path: "{{ golden_base_dir }}/{{ inventory_hostname }}_golden.txt"
  delegate_to: localhost

- name: Get startup config (live, without backup)
  cisco.ios.ios_command:
    commands:
      - show startup-config
  register: startup_config
  when: ansible_network_os == 'cisco.ios.ios'

- name: Get ASA startup config
  cisco.asa.asa_command:
    commands:
      - show startup-config
  register: startup_config
  when: ansible_network_os == 'cisco.asa.asa'

- name: Get FXOS startup config
  cisco.fxos.fxos_command:
    commands:
      - show startup-config
  register: startup_config
  when: ansible_network_os == 'cisco.fxos.fxos'

- name: Read golden config from file
  ansible.builtin.slurp:
    src: "{{ golden_config_path }}"
  register: golden_config

- name: Decode and prepare configs
  ansible.builtin.set_fact:
    current_config_lines: "{{ startup_config.stdout[0] | split('\n') | map('trim') | list }}"
    golden_config_lines: "{{ golden_config.content | b64decode | split('\n') | map('trim') | list }}"

- name: Determine if there are differences
  ansible.builtin.set_fact:
    has_diff: >-
      {{
        (golden_config_lines | difference(current_config_lines)) | length > 0
        or
        (current_config_lines | difference(golden_config_lines)) | length > 0
      }}

- name: Generate visually formatted config diff
  ansible.builtin.set_fact:
    config_diff_text: |
      ─────────────────────────────────────────────────────────────
      🖥️ Host: {{ inventory_hostname }}
      📄 Golden Config: {{ golden_config_path }}
      📅 Timestamp: {{ date_tag }}
      ─────────────────────────────────────────────────────────────

      🔻 Missing (in Golden but not in Live):
      {% set removed = golden_config_lines | difference(current_config_lines) %}
      {% if removed %}
      {% for line in removed %}
        - [Line {{ golden_config_lines.index(line) + 1 }}] {{ line }}
      {% endfor %}
      {% else %}
        ✅ None
      {% endif %}

      ─────────────────────────────────────────────────────────────

      🔺 Added (in Live but not in Golden):
      {% set added = current_config_lines | difference(golden_config_lines) %}
      {% if added %}
      {% for line in added %}
        + [Line {{ current_config_lines.index(line) + 1 }}] {{ line }}
      {% endfor %}
      {% else %}
        ✅ None
      {% endif %}

      ─────────────────────────────────────────────────────────────
      ✅ End of diff for {{ inventory_hostname }}
  when: has_diff

- name: Save config diff to file
  ansible.builtin.copy:
    dest: "{{ output_dir }}/{{ inventory_hostname }}_config_diff_{{ date_tag }}.txt"
    content: "{{ config_diff_text }}"
  when: has_diff
  delegate_to: localhost

- name: Collect all diffs for email
  ansible.builtin.set_fact:
    all_diffs: "{{ groups['all'] | map('extract', hostvars, 'config_diff_text') | select('defined') | list }}"
  run_once: true

- name: Combine all diffs into report
  ansible.builtin.set_fact:
    email_body: |
      🔧 CONFIGURATION DIFF REPORT — SUMMARY
      ===================================================
      🕒 Date: {{ date_tag }}
      📬 Recipients: {{ email_to }}
      ===================================================

      {% for diff in all_diffs %}
      {{ diff }}
      {% endfor %}

      ===================================================
      📢 END OF REPORT
  run_once: true

- name: Send email with config diffs
  ansible.builtin.mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    to: "{{ email_to }}"
    subject: "🛠 Config Diff Report – {{ date_tag }}"
    body: "{{ email_body }}"
    secure: always
    sender: root
    timeout: 20
    charset: utf-8
  run_once: true
  delegate_to: localhost
