---
- name: Compare Cisco ASA firewall config against golden config
  hosts: asa
  gather_facts: no
  connection: network_cli

  vars_files:
    - ../vars/common_vars.yml

  roles:
    - compare_config
