---
- name: Compare Cisco IOS switch config against golden config
  hosts: switches
  gather_facts: no
  connection: network_cli

  vars_files:
    - ../vars/common_vars.yml

  roles:
    - compare_config
