- name: Backup Cisco configs to golden directory
  hosts: all
  gather_facts: no
  connection: network_cli
  vars:
    golden_output_dir: "/runner/project/Configs/Git_Golden_Configs"

  tasks:
    - name: Ensure local golden config dir exists on control node
      file:
        path: "{{ golden_output_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Get running config from Cisco IOS device
      cisco.ios.ios_command:
        commands:
          - show startup-config
      when: ansible_network_os == 'cisco.ios.ios'
      register: startup_config_ios

    - name: Get startup config from Cisco ASA device
      cisco.asa.asa_command:
        commands:
          - show startup-config
      when: ansible_network_os == 'cisco.asa.asa'
      register: startup_config_asa

    - name: Save IOS config locally
      copy:
        content: "{{ startup_config_ios.stdout[0] | default('') }}"
        dest: "{{ golden_output_dir }}/{{ inventory_hostname }}.txt"
      when: ansible_network_os == 'cisco.ios.ios'
      delegate_to: localhost

    - name: Save ASA config locally
      copy:
        content: "{{ startup_config_asa.stdout[0] | default('') }}"
        dest: "{{ golden_output_dir }}/{{ inventory_hostname }}.txt"
      when: ansible_network_os == 'cisco.asa.asa'
      delegate_to: localhost
