all:
  parkwide:
    switches:
      hosts:
        172.16.16.20:
        172.16.16.21:
      vars:
        ansible_network_os: cisco.ios.ios
        platform: ios
    firewalls:
      hosts:
        172.16.16.19:
      vars:
        ansible_network_os: cisco.asa.asa
        platform: asa
