all:
  children:
    cisco_switches:
      hosts:
        172.16.16.20:
        172.16.16.21:
          ansible_network_os: cisco.ios.ios
          platform: ios

    cisco_asa:
      hosts:
        172.16.16.19:
          ansible_network_os: cisco.ios.ios
          platform: asa